module.exports = {
  future: {
    // removeDeprecatedGapUtilities: true,
    // purgeLayersByDefault: true,
  },
  purge: [],
  theme: {
    fontFamily: {
      'sans': ['Plex Sans',
               'system-ui',
               'BlinkMacSystemFont',
               '-apple-system',
               'Segoe UI',
               'Roboto',
               'Oxygen',
               'Ubuntu',
               'Cantarell',
               'Fira Sans',
               'Droid Sans',
               'Helvetica Neue',
               'sans-serif'],
      'mono': ['Plex Mono',
               'Menlo',
               'Monaco',
               'Consolas',
               'Liberation Mono',
               'Courier New',
               'monospace'],
    },
    inset: {
      '16': '-4rem',
      '20': '-5rem',
      '24': '-6rem',
      '32': '-8rem',
      '40': '-10rem',
      '48': '-12rem',
      '56': '-14rem',
      '64': '-16rem',
    },
    extend: {},
  },
  variants: {
    textColor: ['responsive', 'hover', 'visited'],
    borderWidth: ['responsive', 'hover', 'visited'],
  },
  plugins: [],
};